---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  error = FALSE,
  warning = FALSE,
  comment = "#>"
)
```

# Análise de dados macrofitas-cpfl

### [Análise multivariada](https://arpanosso.github.io/macrofitas-cpfl/Docs/analise-multivariada.html)

### [Análise de variância - Solo](https://arpanosso.github.io/macrofitas-cpfl/Docs/analise-varianca.html)

### [Análise de variância -Crescimento Braquiária](https://arpanosso.github.io/macrofitas-cpfl/Docs/analise-crescimento.html)

## Carregando Pacotes

```{r}
library(tidyverse)
source("R/function.R")
```

## Carregando o banco de dados

```{r}
quimica <- readr::read_rds("data/quimica-macrofita")
```


### Cálculo da estatística descritiva
```{r}
quimica |> 
  group_by(data, amostra) |> 
  summarise(across(where(is.numeric),estatisticas)) |> 
  mutate(estatistica = c("Media","Mediana","Desv-pad","CV","CA","CC"),
         .after = amostra) |> 
  writexl::write_xlsx("outputs/estat-desc-quimica.xlsx")
```


```{r}
solo <- readr::read_rds("data/solo-macrofita")
glimpse(solo)
```


```{r}
braquiaria <- readr::read_rds("data/crescimento-braquiaria")
glimpse(braquiaria)
```
