---
title: "Análise de variância"
output: html_document
date: "2024-09-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  error = FALSE,
  warning = FALSE,
  comment = "#>"
)
```


## Carregando Pacotes
```{r}
library(tidyverse)
library(ExpDes.pt)
```

## Carregando dados
```{r}
data_set <- read_rds("../data/crescimento-braquiaria")
glimpse(data_set)
```

```{r}
data_set_aux <- data_set %>% 
  filter(especie != "TESTE")
planta <- data_set_aux %>% 
  pull(especie)
dose <- data_set_aux %>% 
  pull(dose)
rep <- data_set_aux %>% 
  pull(repeticao)
```

```{r}
variaveis <- data_set %>% 
  select(altura:raiz) %>% 
  names()
for(i in seq_along(variaveis)){
  print("##########################################")
  print(paste("ANOVA para: ",variaveis[i]))
  print("##########################################")
  data_set %>% 
    select(variaveis[i])
  
  respad <- data_set %>% 
    filter(especie == "TESTE") %>%
    select(variaveis[i]) %>% 
    pull(variaveis[i])
  resp <- data_set_aux %>% 
    select(variaveis[i]) %>% 
    pull(variaveis[i])
  fat2.ad.dic(planta,dose,rep,resp,respad,
              fac.names = c("Planta","Dose"))
}

```

