---
title: "Análise Multivariada"
output: html_document
date: "2024-09-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  error = FALSE,
  warning = FALSE,
  comment = "#>"
)
```

## Carregando pacotes

```{r}
library(tidyverse)
library(corrplot)
library(vegan)
source("../R/function.R")
theme_set(theme_bw())
```

## Carregando dados

```{r}
data_set <- read_rds("../data/quimica-macrofita")
```


## Tabela da estatística descritiva
```{r}
data_set |> 
  mutate(data = ymd(data)) |> 
  filter(data == "2018-02-01") |> 
  group_by(amostra) |> 
  summarise(across(where(is.numeric),estatisticas)) |> 
  mutate(estatistica = c("Media","Mediana","Desv-pad","CV","CA","CC"),
         .after = amostra) |> 
  gt::gt()
```
```{r}
data_set |> 
  mutate(data = ymd(data)) |> 
  filter(data == "2018-06-01") |> 
  group_by(amostra) |> 
  summarise(across(where(is.numeric),estatisticas)) |> 
  mutate(estatistica = c("Media","Mediana","Desv-pad","CV","CA","CC"),
         .after = amostra) |> 
  gt::gt()
```
## Existem diferenças significativas entre as médias dos nutrientes dentro de uma data e entre as datas?

```{r}
data_set |> 
  pivot_longer(n:pb, 
               names_to = "variable", 
               values_to = "value") |> 
  group_by(variable) |> 
  nest() -> data_set_nest
data_set_nest$data[[1]]

data_set_nest <- data_set_nest |> 
  mutate(
    anova = map(data,my_t_test)
  )
data_set_nest$anova[[1]]
data_set_nest |> 
  unnest(anova) |> 
  select(-data) |> 
  gt::gt()
```


```{r}
datas <- data_set %>% 
  pull(data) %>% 
  unique()
glimpse(data_set)
```


```{r, echo=FALSE}
ng <- c(2,4)
for(i in seq_along(datas)){
  data_set_aux <- data_set %>% 
    filter(data == datas[i]) %>% 
    select(n:pb)
  
  nomes  <- data_set %>% 
    filter(data == datas[i]) %>%  
    pull(amostra)
  
  mc <- cor(data_set_aux)
  print("##########################################")
  print(paste0("     Data ",datas[i]))
  print("##########################################")
  print("======== Análise de correlação linear ========== ")
  corrplot::corrplot(mc)
  
  print("======== Análise de Agrupamento Hierárquico ========== ")
  da_pad<-decostand(data_set_aux, 
                    method = "standardize",
                    na.rm=TRUE)
  da_pad_euc<-vegdist(da_pad,"euclidean") 
  da_pad_euc_ward<-hclust(da_pad_euc, method="ward.D")
  plot(da_pad_euc_ward, 
       ylab="Distância Euclidiana",
       xlab="Acessos", hang=-1,
       col="blue", las=1,
       cex=.6,lwd=1.5);box()
  grupo<-cutree(da_pad_euc_ward,ng[i])
  
  print("======== Análise de Componentes Principais ========== ")
  pca <-  prcomp(da_pad,scale.=TRUE)
  # Autovalores
  eig<-pca$sdev^2
  print("==== Autovalores ====")
  print(round(eig,3))
  print("==== % da variância explicada ====")
  ve<-eig/sum(eig)
  print(round(ve,4))
  print("==== % da variância explicada acumulada ====")
  print(round(cumsum(ve),4)*100)
  print("==== Poder Discriminante ====")
  mcor<-cor(da_pad,pca$x)
  corrplot(mcor)
  print("==== screeplot ====")
  screeplot(pca)
  abline(h=1)
  print("==== Gráfico Biplot ====")
  pc1V<-cor(da_pad,pca$x)[,1]/sd(cor(da_pad,pca$x)[,1])
  pc2V<-cor(da_pad,pca$x)[,2]/sd(cor(da_pad,pca$x)[,2])
  pc3V<-cor(da_pad,pca$x)[,3]/sd(cor(da_pad,pca$x)[,3])
  pc1c<-pca$x[,1]/sd(pca$x[,1])
  pc2c<-pca$x[,2]/sd(pca$x[,2])
  pc3c<-pca$x[,3]/sd(pca$x[,3])
  nv<-ncol(data_set_aux) # número de variáveis utilizadas na análise
  # gráfico biplot
  bip<-data.frame(pc1c,pc2c,pc3c,grupo)
  texto <- data.frame(
    x = pc1V,
    y = pc2V,
    z = pc3V,
    label = names(data_set_aux)
  )
  
  graf <- bip %>% 
    ggplot(aes(x=pc1c,y=pc2c,color=as_factor(grupo)))+
    geom_point(aes(shape = as_factor(grupo), color = as_factor(grupo)), size = 3)+ theme_minimal() +
    scale_shape_manual(values=16:(16+4-1))+
    #annotate(geom="text", x=pc1V, y=pc2V, label=names(pc1V),
    #            color="black",font=3)+
    geom_vline(aes(xintercept=0),
               color="black", size=1)+
    geom_hline(aes(yintercept=0),
               color="black", size=1)+
    annotate(geom="segment",
             x=rep(0,length(data_set_aux)),
             xend=texto$x,
             y=rep(0,length(data_set_aux)),
             yend=texto$y,color="black",lwd=.5)+
    geom_label(data=texto,aes(x=x,y=y,label=label),
               color="black",angle=0,fontface="bold",size=4,fill="white")+
    labs(x=paste("CP1 (",round(100*ve[1],2),"%)",sep=""),
         y=paste("CP2 (",round(100*ve[2],2),"%)",sep=""),
         color="",shape="")+
    theme(legend.position = "top")
  print(graf)
  
  print("==== Tabela da correlação dos atributos com cada PC ====")
  ck<-sum(pca$sdev^2>=0.98)
  tabelapca<-vector()
  for( l in 1:ck) tabelapca<-cbind(tabelapca,mcor[,l])
  colnames(tabelapca)<-paste(rep(c("PC"),ck),1:ck,sep="")
  pcat<-round(tabelapca,3)
  tabelapca<-tabelapca[order(abs(tabelapca[,1])),]
  print(tabelapca)
}
```

